spring:
  datasource:
    username: postgres
    password: qwerty
    url: jdbc:postgresql://localhost:5432/timetable
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update


jwt:
  security:
    secret: soymun
    validate : 3600000