spring:
  datasource:
    username: postgres
    password: qwerty
    url: jdbc:postgresql://localhost:5432/timetable

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: off
jwt:
  security:
    secret: soymun
    validate : 3600000